#spring:
#  datasource:
#    dynamic:
#      primary: master
#      strict: false
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/master?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 123456
#        slave1:
#          url: jdbc:mysql://localhost:3306/slave1?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 123456
#        slave2:
#          url: jdbc:mysql://localhost:3306/slave2?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 123456

# 自定义配置 多数据源 读写分离
spring:
  datasource:
    write:
      jdbc-url: jdbc:mysql://localhost:3306/master?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    read1:
      jdbc-url: jdbc:mysql://localhost:3306/slave1?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    read2:
      jdbc-url: jdbc:mysql://localhost:3306/slave2?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传相关配置
file:
  # 本地上传服务配置
  local:
    # 上传文件访问路径
    access-path: /file/**
    # 上传文件保存路径，注意：最后带上反斜杠
    upload-path: /Users/chouchou/upload/boot/
    # 上传文件访问URL前缀
    access-url: http://localhost:${server.port}/api/file

# 日志配置，logback-spring.xml中会引用以下变量
logback-spring:
  # 日志文件目录
  path: logs

