server:
  port: 9091

spring:
  main:
    web-application-type: REACTIVE
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 启用服务发现
          enabled: true
          lower-case-service-id: true
      enabled: true
      routes:
        - id: login-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/login-service/**
          filters:
            - StripPrefix=2
        - id: system
          uri: http://localhost:8092
          predicates:
            - Path=/api/system-service/**
          filters:
            - StripPrefix=2
        - id: user
          uri: http://localhost:8093
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
#logging:
#    file:
#        name: D:/log/gateway.log
#    level:
#        springfox: error
#        cn.edu.sgu.www.gateway: debug

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 用户服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /api/user-service/v3/api-docs?group=default
        service-name: user-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /api/user-service
        order: 2
      - name: 系统服务
        url: /api/system-service/v3/api-docs?group=default
        service-name: system-service
        # 路由前缀
        context-path: /api/system-service
        order: 3
      - name: 登录服务
        url: /api/login-service/v3/api-docs?group=default
        service-name: login-service
        # 路由前缀
        context-path: /api/login-service
        order: 4
  setting:
    # 自定义底部
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: MIT License | Copyright © 2019-2023 [chou401](https://chou401.io22222)