# dynamic-datasource 注解 DS 读写分离
#spring:
#  datasource:
#    dynamic:
#      primary: write
#      strict: false
#      datasource:
#        write:
#          url: jdbc:mysql://localhost:3306/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 3306
#        read1:
#          url: jdbc:mysql://localhost:3307/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 3307
#        read2:
#          url: jdbc:mysql://localhost:3308/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 3308

# 自定义配置 aop 多数据源 读写分离 需要编写代码
#spring:
#  datasource:
#    write:
#      jdbc-url: jdbc:mysql://localhost:3306/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 3306
#    read1:
#      jdbc-url: jdbc:mysql://localhost:3307/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 3307
#    read2:
#      jdbc-url: jdbc:mysql://localhost:3308/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 3308

# 使用 shardingsphere-jdbc
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yaml

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传相关配置
file:
  # 本地上传服务配置
  local:
    # 上传文件访问路径
    access-path: /file/**
    # 上传文件保存路径，注意：最后带上反斜杠
    upload-path: /Users/chouchou/upload/boot/
    # 上传文件访问URL前缀
    access-url: http://localhost:${server.port}/api/file

# 日志配置，logback-spring.xml中会引用以下变量
logback-spring:
  # 日志文件目录
  path: logs

