#mode:
#    type: Standalone
#    repository:
#        type: JDBC
dataSources:
    ds_0:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 3306
    ds_1:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3307/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 3307
    ds_2:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3308/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 3308

rules:
- !READWRITE_SPLITTING
    dataSources:
        readwrite_ds:
            writeDataSourceName: ds_0
            readDataSourceNames:
                - ds_1
                - ds_2
            transactionalReadQueryStrategy: PRIMARY
            loadBalancerName: random
    loadBalancers:
        random:
            type: RANDOM
- !SINGLE
    tables:
        - "*.*"
#    tables:
#        sys_user:
#            actualDataNodes: ds_$->{0..1}.sys_user
#            databaseStrategy:
#                standard:
#                    shardingColumn: id
#                    shardingAlgorithmName: id_inline
#        defaultDatabaseStrategy:
#            standard:
#                shardingColumn: id
#                shardingAlgorithmName: database_inline
#        shardingAlgorithms:
#            database_inline:
#                type: INLINE
#                props:
#                    algorithm-expression: ds_$->{id % 2}
#            id_inline:
#                type: INLINE
#                props:
#                    algorithm-expression: ds_$->{id % 2}
props:
    sql-show: true


