# dynamic-datasource 注解 读写分离
#spring:
#  datasource:
#    dynamic:
#      primary: write
#      strict: false
#      datasource:
#        write:
#          url: jdbc:mysql://localhost:3306/master?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        read1:
#          url: jdbc:mysql://localhost:3306/slave1?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        read2:
#          url: jdbc:mysql://localhost:3306/slave2?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#      strategy: com.baomidou.dynamic.datasource.strategy.LoadBalanceDynamicDataSourceStrategy

# 自定义配置 多数据源 读写分离
spring:
  datasource:
    write:
      jdbc-url: jdbc:mysql://localhost:3306/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 3306
    read1:
      jdbc-url: jdbc:mysql://localhost:3307/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 3307
    read2:
      jdbc-url: jdbc:mysql://localhost:3308/boot?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 3308

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传相关配置
file:
  # 本地上传服务配置
  local:
    # 上传文件访问路径
    access-path: /file/**
    # 上传文件保存路径，注意：最后带上反斜杠
    upload-path: /Users/chouchou/upload/boot/
    # 上传文件访问URL前缀
    access-url: http://localhost:${server.port}/api/file

# 日志配置，logback-spring.xml中会引用以下变量
logback-spring:
  # 日志文件目录
  path: logs

